BEGIN;
SET LOCAL lock_timeout = '5s';
ALTER TABLE cms_posts ADD COLUMN IF NOT EXISTS view_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE cms_posts ADD COLUMN IF NOT EXISTS meta_title TEXT NOT NULL DEFAULT '';
ALTER TABLE cms_posts ADD COLUMN IF NOT EXISTS meta_description TEXT NOT NULL DEFAULT '';
COMMIT;
