BEGIN;

ALTER TABLE expenses ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'RECORDED' CHECK (status IN ('RECORDED','VERIFIED','APPROVED','REJECTED'));
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS verified_by TEXT REFERENCES users(id);
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS verified_by_name VARCHAR(120);
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS approved_by TEXT REFERENCES users(id);
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS approved_by_name VARCHAR(120);
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;

COMMIT;
