const select = (key, label, options, required = false) => ({ key, label, type: 'select', options, required })
const field = (key, label, type = 'text', required = false) => ({ key, label, type, required })

export const registryResources = {
  athletes: { label: 'Athlete', fields: [field('federation_id','Federation','federation',true),field('full_name','Full Name','text',true),select('gender','Gender',['MALE','FEMALE','OTHER','NOT_STATED'],true),field('date_of_birth','Date of Birth','date',true),field('national_id_passport','National ID / Passport'),field('district','District'),select('region','Region',['North','East','Central','West']),field('club','Club'),field('discipline','Discipline / Sport','text',true),select('national_team_status','National Team Status',['NO','DEVELOPMENT','SENIOR','FORMER']),select('status','Status',['ACTIVE','INACTIVE','SUSPENDED','RETIRED']),field('consent_basis','Consent Basis'),field('age_category','Age Category'),field('phone_contact','Phone'),field('email_address','Email','email'),field('next_of_kin','Next of Kin'),field('emergency_contact','Emergency Contact'),field('education_institution','School / Institution'),field('highest_education_level','Highest Education Level'),field('sports_scholarship_status','Sports Scholarship','boolean'),field('current_occupation','Current Occupation')] },
  clubs: { label: 'Club or Academy', fields: [field('federation_id','Federation','federation',true),field('name','Club Name','text',true),field('acronym','Acronym','text',true),field('contact_person','Contact Person'),field('email','Contact Email','email'),field('phone','Contact Phone'),field('district','District'),select('region','Region',['North','East','Central','West']),field('date_founded','Date Founded','date'),select('status','Status',['ACTIVE','INACTIVE','SUSPENDED'])] },
  coaches: { label: 'Coach', fields: [field('federation_id','Federation','federation',true),field('full_name','Full Name','text',true),field('certification_level','Certification Level','text',true),field('license_number','License Number','text',true),field('expiry_date','Expiry Date','date'),select('status','Status',['ACTIVE','INACTIVE','SUSPENDED']),field('phone','Phone'),field('email','Email','email',true)] },
  competitions: { label: 'Competition', fields: [field('federation_id','Federation','federation',true),field('name','Competition Name','text',true),field('venue','Venue','text',true),field('host_country','Host Country'),select('level','Competition Level',['DISTRICT','REGIONAL','NATIONAL','EAST_AFRICAN','AFRICAN','COMMONWEALTH','OLYMPIC','WORLD_CHAMPIONSHIP','CONTINENTAL','INTERNATIONAL'],true),field('starts_on','Starts On','date',true),field('ends_on','Ends On','date',true),field('returned_on','Returned On','date'),field('athlete_count','Athlete Count','number'),field('official_count','Official Count','number'),select('status','Status',['DRAFT','SUBMITTED','APPROVED','CANCELLED'])] },
  'competition-results': { label: 'Competition Result', fields: [field('competition_id','Competition','competition',true),field('athlete_id','Registered Athlete','athlete'),field('athlete_name','Athlete Name','text',true),field('event','Event','text',true),field('position','Position','number'),field('time_result','Time Result'),field('distance_result','Distance Result'),field('weight_result','Weight Result'),field('score_result','Score Result'),field('ranking_result','Ranking Result'),field('is_national_record','National Record','boolean'),field('is_personal_best','Personal Best','boolean'),field('is_seasonal_best','Seasonal Best','boolean')] },
  medals: { label: 'Medal', fields: [field('competition_id','Competition','competition',true),field('federation_id','Federation','federation',true),field('athlete_id','Registered Athlete','athlete'),field('athlete_name','Athlete Name','text',true),field('event','Event','text',true),field('country','Host Country','text',true),field('won_on','Date Won','date',true),select('medal_type','Medal Type',['GOLD','SILVER','BRONZE'],true),field('coach_responsible','Coach Responsible'),field('team_manager','Team Manager'),field('funding_source','Funding Source'),select('status','Status',['DRAFT','SUBMITTED','APPROVED','VOIDED']),select('level','Level',['DISTRICT','REGIONAL','NATIONAL','EAST_AFRICAN','AFRICAN','COMMONWEALTH','OLYMPIC','WORLD_CHAMPIONSHIP','CONTINENTAL','INTERNATIONAL']),field('is_team_event','Team Event','boolean'),field('prize_money','Prize Money','number'),select('ncs_recognition_status','NCS Recognition',['PENDING','APPROVED','REJECTED'])] },
  talent: { label: 'Talent Pathway', fields: [field('federation_id','Federation','federation',true),field('athlete_id','Registered Athlete','athlete'),field('athlete_name','Athlete Name','text',true),field('age_at_identification','Age at Identification','number',true),field('school','School / Institution'),field('district','District','text',true),select('region','Region',['North','East','Central','West']),field('identified_by','Identified By','text',true),field('identified_on','Identification Date','date',true),select('status','Status',['IDENTIFIED','ASSESSED','SELECTED','NATIONAL_TEAM','CLOSED']),field('talent_centre','Talent Centre'),select('talent_category','Talent Category',['AMATEUR','EMERGING','ELITE']),field('recommended_pathway','Recommended Pathway','textarea'),select('scholarship_status','Scholarship Status',['NONE','APPLIED','ACTIVE','EXPIRED'])] },
  'national-team': { label: 'National Team Appearance', fields: [field('athlete_id','Athlete','athlete',true),field('team_name','Team Name','text',true),select('category','Category',['SENIOR','DEVELOPMENT','JUNIOR'],true),field('first_call_up_on','First Call-up','date'),field('last_appearance_on','Last Appearance','date'),field('appearances_count','Appearances','number'),field('notes','Notes','textarea')] },
  'technical-officials': { label: 'Technical Official', fields: [field('federation_id','Federation','federation',true),field('full_name','Full Name','text',true),select('official_type','Official Type',['REFEREE','UMPIRE','JUDGE','ASSESSOR','OTHER'],true),field('level','Level','text',true),field('certification','Certification','text',true),field('valid_until','Valid Until','date'),select('status','Status',['ACTIVE','INACTIVE','SUSPENDED'])] },
  'medical-records': { label: 'Medical Record', sensitive: true, fields: [field('athlete_id','Athlete','athlete',true),field('blood_group','Blood Group'),field('allergies','Allergies','textarea'),field('injury_history','Injury History','textarea'),select('current_injury_status','Current Injury Status',['FIT','INJURED','RECOVERING']),field('medical_insurance','Medical Insurance','textarea')] },
  'safeguarding-records': { label: 'Safeguarding Record', sensitive: true, fields: [field('athlete_id','Athlete','athlete',true),field('guardian_details','Guardian Details','json'),field('manager_details','Manager Details','json'),field('safeguarding_officer_assigned','Safeguarding Officer','user'),field('consent_forms_url','Consent Forms URL','url'),field('anti_doping_education_completed','Anti-Doping Education Completed','boolean')] },
  'anti-doping': { label: 'Anti-Doping Compliance', sensitive: true, fields: [field('athlete_id','Athlete','athlete',true),select('testing_status','Testing Pool Status',['NOT_TESTED','IN_POOL','TESTED']),field('last_tested_on','Last Tested','date'),field('last_test_result','Last Test Result'),field('wada_education_completed','WADA Education Completed','boolean'),field('suspension_history','Suspension History','textarea')] },
  disbursements: { label: 'Disbursement', fields: [field('federation_id','Federation','federation',true),field('reference','Reference','text',true),field('amount','Amount','number',true),field('currency','Currency','text',true),field('released_on','Released On','date',true),field('accountability_due_on','Accountability Due','date',true),select('status','Status',['PLANNED','RELEASED','PARTIALLY_ACCOUNTED','ACCOUNTED','CANCELLED'])] },
  accountabilities: { label: 'Financial Accountability', fields: [field('federation_id','Federation','federation',true),field('reporting_period_id','Reporting Period ID','text',true),field('currency','Currency','text',true),field('government_grant','Government Grant','number'),field('sponsorship','Sponsorship','number'),field('membership_fees','Membership Fees','number'),field('donations','Donations','number'),field('competitions','Competitions','number'),field('training','Training','number'),field('equipment','Equipment','number'),field('administration','Administration','number'),select('status','Status',['DRAFT','SUBMITTED','NEEDS_CORRECTION','APPROVED','LOCKED'])] },
  equipment: { label: 'Distributed Equipment', fields: [field('federation_id','Federation','federation',true),field('item_name','Equipment Name','text',true),select('unit','Unit',['ITEM','PIECE','PAIR','SET','BOX','CARTON','KIT','BAG'],true),field('quantity_received','Quantity Received','number',true),field('quantity_distributed','Quantity Distributed','number',true)] },
}

export const registryResourceNames = Object.keys(registryResources)
