<template><LayoutDefault title="Database Backup & Restore"><div class="space-y-6">
  <section class="bg-white border border-gray-100 rounded-2xl p-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 class="text-xl font-bold text-primary-800">Verified recovery points</h1><p class="text-sm text-gray-500 mt-1">Backups are checksummed and must pass an isolated restore before production recovery.</p></div><button @click="queue('BACKUP')" class="rounded-xl bg-primary-700 px-5 py-3 text-white font-bold">Create backup now</button></section>
  <section v-if="activeJob" class="rounded-2xl border border-blue-100 bg-blue-50 p-5"><div class="flex justify-between text-sm"><strong>{{ activeJob.job_type }} in progress</strong><span>{{ activeJob.progress }}%</span></div><div class="h-2 bg-white rounded-full mt-3"><div class="h-full bg-blue-600 rounded-full transition-all" :style="{width:activeJob.progress+'%'}"></div></div><p class="text-xs text-blue-800 mt-2">{{ activeJob.message }}</p></section>
  <section class="bg-white border border-gray-100 rounded-2xl overflow-hidden"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-gray-500"><tr><th class="text-left p-4">Backup</th><th class="text-left p-4">Created</th><th class="text-left p-4">Size</th><th class="text-left p-4">Integrity</th><th class="text-right p-4">Actions</th></tr></thead><tbody class="divide-y divide-gray-100"><tr v-for="backup in backups" :key="backup.id"><td class="p-4"><strong class="text-primary-800">{{ backup.file_name }}</strong><p class="font-mono text-[10px] text-gray-400 mt-1">{{ backup.checksum }}</p></td><td class="p-4 text-gray-500">{{ date(backup.created_at) }}</td><td class="p-4">{{ bytes(backup.size_bytes) }}</td><td class="p-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold" :class="backup.status==='VERIFIED'?'bg-green-100 text-green-700':'bg-amber-100 text-amber-700'">{{ backup.status }}</span></td><td class="p-4 text-right space-x-2"><button @click="queue('VERIFY',backup.id)" class="rounded-lg border px-3 py-2 font-semibold">Verify</button><button :disabled="backup.status!=='VERIFIED'" @click="restore(backup.id)" class="rounded-lg bg-red-700 px-3 py-2 text-white font-semibold disabled:opacity-30">Restore</button></td></tr><tr v-if="!backups.length"><td colspan="5" class="p-10 text-center text-gray-400">No backup records yet.</td></tr></tbody></table></div></section>
  <section class="bg-white border border-gray-100 rounded-2xl p-6"><h2 class="font-bold text-primary-800">Recent jobs</h2><div class="mt-4 space-y-2"><div v-for="job in jobs.slice(0,10)" :key="job.id" class="flex items-center justify-between rounded-xl bg-gray-50 p-3 text-sm"><span><strong>{{ job.job_type }}</strong> · {{ job.message }}</span><span class="font-bold" :class="job.status==='FAILED'?'text-red-600':job.status==='SUCCEEDED'?'text-green-600':'text-blue-600'">{{ job.status }}</span></div></div></section>
</div></LayoutDefault></template>
<script setup>
import { computed,onBeforeUnmount,onMounted,ref } from 'vue';import LayoutDefault from '@/components/layout/LayoutDefault.vue';import apiClient from '@/api/client.js'
const backups=ref([]),jobs=ref([]);let timer;const activeJob=computed(()=>jobs.value.find(j=>j.status==='RUNNING'||j.status==='PENDING'))
async function load(){const r=await apiClient.get('/api/v1/admin/system/backups');backups.value=r.data.data?.backups||[];jobs.value=r.data.data?.jobs||[]}
async function queue(action,backup_id=null,confirmation=''){await apiClient.post('/api/v1/admin/system/backups/jobs',{action,backup_id,confirmation});await load()}
async function restore(id){if(prompt('Enable maintenance mode first, then type RESTORE VERIFIED BACKUP')!=='RESTORE VERIFIED BACKUP')return;await queue('RESTORE',id,'RESTORE VERIFIED BACKUP')}
const date=v=>new Date(v).toLocaleString(),bytes=v=>{let n=v||0,i=0,u=['B','KB','MB','GB'];while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n.toFixed(1)} ${u[i]}`}
onMounted(()=>{load();timer=setInterval(load,3000)});onBeforeUnmount(()=>clearInterval(timer))
</script>
