<template>
  <LayoutDefault :title="definition.title">
    <div class="space-y-5">
      <section class="admin-card"><div class="admin-card-body flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p class="text-xs font-bold uppercase tracking-wider text-primary-700">NSMIS registry</p><h1 class="mt-1 text-xl font-bold text-gray-900">{{ definition.title }}</h1><p class="mt-1 text-sm text-gray-500">{{ definition.description }}</p></div><button class="btn-primary" @click="openCreate">Add record</button></div></section>
      <div v-if="message" role="status" class="rounded-lg border border-green-200 bg-green-50 p-3 text-sm text-green-700">{{ message }}</div>
      <div v-if="error" role="alert" class="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{{ error }}</div>
      <section class="admin-card overflow-hidden">
        <div class="admin-card-header flex-wrap gap-3"><h2 class="font-semibold text-gray-900">Records <span class="text-xs font-normal text-gray-400">({{ meta.total }})</span></h2><div class="flex gap-2"><input v-model="search" class="rounded-lg border-gray-300 text-sm" placeholder="Search records" @keyup.enter="load"/><button class="rounded-lg border px-3 text-sm font-semibold" @click="load">Search</button></div></div>
        <div v-if="loading" class="p-12 text-center text-sm text-gray-500">Loading records…</div>
        <div v-else class="overflow-x-auto"><table class="w-full"><thead><tr><th v-for="col in definition.columns" :key="col" class="table-th">{{ label(col) }}</th><th class="table-th"><span class="sr-only">Actions</span></th></tr></thead><tbody class="divide-y divide-gray-100"><tr v-for="row in records" :key="row.id"><td v-for="col in definition.columns" :key="col" class="table-td"><span v-if="col==='status'" class="inline-flex rounded-full bg-gray-100 px-2 py-1 text-xs font-semibold">{{ display(row[col]) }}</span><span v-else>{{ display(row[col]) }}</span></td><td class="table-td whitespace-nowrap text-right"><button class="mr-3 font-semibold text-primary-700" @click="openEdit(row)">Edit</button><button class="font-semibold text-red-700" @click="remove(row)">Delete</button></td></tr><tr v-if="!records.length"><td :colspan="definition.columns.length+1" class="p-12 text-center text-sm text-gray-500">No records match this selection.</td></tr></tbody></table></div>
        <div v-if="meta.total>meta.per_page" class="admin-card-footer flex justify-end gap-2"><button class="rounded border px-3 py-1 text-sm" :disabled="meta.page===1" @click="page(meta.page-1)">Previous</button><button class="rounded border px-3 py-1 text-sm" :disabled="meta.page*meta.per_page>=meta.total" @click="page(meta.page+1)">Next</button></div>
      </section>
      <div v-if="editing" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" @click.self="editing=null"><section class="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white shadow-xl" role="dialog" aria-modal="true"><div class="admin-card-header"><h2 class="font-bold">{{ editing.id?'Edit':'Add' }} {{ definition.singular }}</h2><button aria-label="Close" @click="editing=null">✕</button></div><form class="admin-card-body grid gap-4 md:grid-cols-2" @submit.prevent="save"><label v-for="field in definition.fields" :key="field.key" class="block text-sm font-medium text-gray-700" :class="field.wide?'md:col-span-2':''">{{ field.label || label(field.key) }}<select v-if="field.options" v-model="form[field.key]" :required="field.required" class="mt-1 block w-full rounded-lg border-gray-300"><option value="">Select…</option><option v-for="x in field.options" :key="x" :value="x">{{ display(x) }}</option></select><select v-else-if="field.source==='federations'" v-model="form[field.key]" :required="field.required" class="mt-1 block w-full rounded-lg border-gray-300"><option value="">Select federation…</option><option v-for="x in federations" :key="x.id" :value="x.id">{{ x.name }}</option></select><select v-else-if="field.source==='periods'" v-model="form[field.key]" :required="field.required" class="mt-1 block w-full rounded-lg border-gray-300"><option value="">Select period…</option><option v-for="x in periods" :key="x.id" :value="x.id">{{ x.name }}</option></select><input v-else v-model="form[field.key]" :type="field.type||'text'" :required="field.required" :min="field.min" class="mt-1 block w-full rounded-lg border-gray-300"/></label><div class="md:col-span-2 flex justify-end gap-3 border-t pt-4"><button type="button" class="rounded-lg border px-4 py-2 text-sm font-semibold" @click="editing=null">Cancel</button><button class="btn-primary" :disabled="saving">{{ saving?'Saving…':'Save record' }}</button></div></form></section></div>
    </div>
  </LayoutDefault>
</template>
<script setup>
import {computed,onMounted,reactive,ref,watch} from 'vue'
import {useRoute} from 'vue-router'
import LayoutDefault from '@/components/layout/LayoutDefault.vue'
import apiClient from '@/api/client.js'
import {useBreadcrumbStore} from '@/stores/breadcrumb.js'
const route=useRoute(),breadcrumb=useBreadcrumbStore(),records=ref([]),federations=ref([]),periods=ref([]),loading=ref(false),saving=ref(false),editing=ref(null),search=ref(''),error=ref(''),message=ref(''),form=reactive({}),meta=reactive({page:1,per_page:25,total:0})
const federation={key:'federation_id',source:'federations',required:true}, period={key:'reporting_period_id',source:'periods',required:true}
const defs={
 'federation-officers':{title:'Federation Leadership',singular:'officer',description:'Maintain current and historical federation office bearers.',columns:['full_name','position','email','term_ends_on'],fields:[federation,{key:'position',required:true,options:['PRESIDENT','VICE_PRESIDENT','GENERAL_SECRETARY','TREASURER','TECHNICAL_DIRECTOR','OTHER']},{key:'position_label'},{key:'full_name',required:true},{key:'email',type:'email'},{key:'phone'},{key:'appointed_on',type:'date'},{key:'term_ends_on',type:'date'}]},
 athletes:{title:'Athlete Registry',singular:'athlete',description:'National athlete master records and federation affiliations.',columns:['athlete_number','full_name','gender','discipline','national_team_status','status'],fields:[federation,{key:'athlete_number'},{key:'full_name',required:true},{key:'gender',required:true,options:['MALE','FEMALE','OTHER','NOT_STATED']},{key:'date_of_birth',type:'date',required:true},{key:'district'},{key:'region'},{key:'club'},{key:'discipline',required:true},{key:'national_team_status',options:['NO','DEVELOPMENT','SENIOR','FORMER']},{key:'status',options:['ACTIVE','INACTIVE','SUSPENDED','RETIRED']}]},
 competitions:{title:'Competitions',singular:'competition',description:'Competition participation, venues and approval state.',columns:['name','venue','level','starts_on','athlete_count','status'],fields:[federation,{key:'name',required:true},{key:'venue',required:true},{key:'host_country'},{key:'level',required:true,options:['NATIONAL','REGIONAL','CONTINENTAL','INTERNATIONAL']},{key:'starts_on',type:'date',required:true},{key:'ends_on',type:'date',required:true},{key:'returned_on',type:'date'},{key:'athlete_count',type:'number',min:0},{key:'official_count',type:'number',min:0},{key:'status',options:['DRAFT','SUBMITTED','APPROVED','CANCELLED']}]},
 medals:{title:'Medal Tracking',singular:'medal',description:'Individual approved medal awards and event attribution.',columns:['athlete_name','event','medal_type','country','won_on','status'],fields:[federation,{key:'competition_id',required:true},{key:'athlete_id'},{key:'athlete_name',required:true},{key:'event',required:true},{key:'country',required:true},{key:'won_on',type:'date',required:true},{key:'medal_type',required:true,options:['GOLD','SILVER','BRONZE']},{key:'coach_responsible'},{key:'team_manager'},{key:'funding_source'},{key:'status',options:['DRAFT','SUBMITTED','APPROVED','VOIDED']}]},
 coaches:{title:'Coach Registry',singular:'coach',description:'Coach certification, licence and expiry monitoring.',columns:['full_name','certification_level','license_number','expiry_date','status'],fields:[federation,{key:'full_name',required:true},{key:'certification_level',required:true},{key:'license_number',required:true},{key:'expiry_date',type:'date'},{key:'status',options:['ACTIVE','INACTIVE','SUSPENDED']}]},
 'technical-officials':{title:'Technical Officials',singular:'official',description:'Referee, umpire, judge and assessor credentials.',columns:['full_name','official_type','level','certification','valid_until','status'],fields:[federation,{key:'full_name',required:true},{key:'official_type',required:true,options:['REFEREE','UMPIRE','JUDGE','ASSESSOR','OTHER']},{key:'level',required:true},{key:'certification',required:true},{key:'valid_until',type:'date'},{key:'status',options:['ACTIVE','INACTIVE','SUSPENDED']}]},
 talent:{title:'Talent Pipeline',singular:'talent record',description:'Identification, assessment, selection and progression.',columns:['athlete_name','district','identified_on','identified_by','status'],fields:[federation,{key:'athlete_id'},{key:'athlete_name',required:true},{key:'age_at_identification',type:'number',min:4,required:true},{key:'school'},{key:'district',required:true},{key:'region'},{key:'identified_by',required:true},{key:'identified_on',type:'date',required:true},{key:'status',options:['IDENTIFIED','ASSESSED','SELECTED','NATIONAL_TEAM','CLOSED']}]},
 'safeguarding-aggregates':{title:'Safeguarding & Gender',singular:'period aggregate',description:'Controlled aggregate reporting without exposing case identities.',columns:['female_athletes','female_coaches','safeguarding_cases','resolved_cases','status'],fields:[federation,period,{key:'female_athletes',type:'number',min:0},{key:'female_coaches',type:'number',min:0},{key:'safeguarding_cases',type:'number',min:0},{key:'resolved_cases',type:'number',min:0},{key:'status',options:['DRAFT','SUBMITTED','APPROVED']}]},
 disbursements:{title:'NCS Disbursements',singular:'disbursement',description:'Funds released and accountability due dates.',columns:['reference','amount','currency','released_on','accountability_due_on','status'],fields:[federation,{key:'reference',required:true},{key:'amount',type:'number',min:0,required:true},{key:'currency'},{key:'released_on',type:'date',required:true},{key:'accountability_due_on',type:'date',required:true},{key:'status',options:['PLANNED','RELEASED','PARTIALLY_ACCOUNTED','ACCOUNTED','CANCELLED']}]},
 accountabilities:{title:'Financial Accountability',singular:'financial report',description:'Revenue, expenditure and review status by reporting period.',columns:['currency','government_grant','sponsorship','competitions','training','status'],fields:[federation,period,{key:'currency'},...['government_grant','sponsorship','membership_fees','donations','competitions','training','equipment','administration'].map(key=>({key,type:'number',min:0})),{key:'status',options:['DRAFT','SUBMITTED','NEEDS_CORRECTION','APPROVED','LOCKED']}]},
 equipment:{title:'Equipment Inventory',singular:'equipment item',description:'Equipment received, distributed and remaining on hand.',columns:['item_name','unit','quantity_received','quantity_distributed'],fields:[federation,{key:'item_name',required:true},{key:'unit'},{key:'quantity_received',type:'number',min:0},{key:'quantity_distributed',type:'number',min:0}]}
}
const definition=computed(()=>defs[route.params.resource]||defs.athletes)
function label(v){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())} function display(v){if(v===null||v===undefined||v==='')return '—';return String(v).replaceAll('_',' ')}
function normalize(){for(const k of Object.keys(form))delete form[k];for(const f of definition.value.fields)form[f.key]=f.type==='number'?0:''}
function openCreate(){normalize();editing.value={};message.value='';error.value=''} function openEdit(row){normalize();Object.assign(form,row);editing.value=row;message.value='';error.value=''}
async function load(){loading.value=true;error.value='';try{const r=await apiClient.get(`/api/v1/nsmis/${route.params.resource}/`,{params:{page:meta.page,per_page:meta.per_page,search:search.value}});records.value=r.data?.data?.items||[];Object.assign(meta,r.data?.data?.pagination||{})}catch(e){error.value=e.response?.data?.error?.message||'Records could not be loaded.'}finally{loading.value=false}}
async function save(){saving.value=true;error.value='';try{const payload={};for(const f of definition.value.fields){let v=form[f.key];if(f.type==='number'&&v!=='')v=Number(v);if(v!==''&&v!==undefined)payload[f.key]=v}if(editing.value.id)await apiClient.put(`/api/v1/nsmis/${route.params.resource}/${editing.value.id}`,payload);else await apiClient.post(`/api/v1/nsmis/${route.params.resource}/`,payload);editing.value=null;message.value='Record saved successfully.';await load()}catch(e){error.value=e.response?.data?.error?.message||'Record could not be saved.'}finally{saving.value=false}}
async function remove(row){if(!confirm('Delete this record? Historical references may prevent deletion.'))return;try{await apiClient.delete(`/api/v1/nsmis/${route.params.resource}/${row.id}`);message.value='Record deleted.';await load()}catch(e){error.value=e.response?.data?.error?.message||'Record could not be deleted.'}}
function page(p){meta.page=p;load()} async function referenceData(){const [f,p]=await Promise.allSettled([apiClient.get('/api/v1/nsmis/federations'),apiClient.get('/api/v1/nsmis/reporting-periods',{params:{open:false}})]);if(f.status==='fulfilled')federations.value=f.value.data?.data||[];if(p.status==='fulfilled')periods.value=p.value.data?.data||[]}
async function initialize(){meta.page=1;breadcrumb.set(definition.value.title);await referenceData();await load()} watch(()=>route.params.resource,initialize);onMounted(initialize)
</script>
